FROM node:lts-buster-slim as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json .
COPY yarn.lock .

RUN yarn install 

COPY . .

RUN yarn run build

FROM nginx:alpine
COPY --from=production /usr/src/app/build/ /usr/share/nginx/html
# Copy the default nginx.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
